name: "Hello World"
description: "Greet someone"
runs:
  using: "composite"
  steps:
    - run: echo Hello Panda Script.
      shell: bash
    - run: source index.sh && panda_health_check
      shell: bash
    - run: panda_health_check
      shell: bash
