name: "Hello World"
description: "Greet someone"
runs:
  using: "composite"
  steps:
    - run: echo Hello
      shell: bash
    - run: source index.sh
      shell: bash
    - run: panda_health_check
      shell: bash
    -
